const academicsActionType = {
   SET_ALL_ACADEMICS_ARTICLES: "SET_ALL_ACADEMICS_ARTICLES",
   LIKE_ACADEMICS_ARTICLE: "LIKE_ACADEMICS_ARTICLE",
   ADD_ACADEMICS_ARTICLE: "ADD_ACADEMICS_ARTICLE",
   EDIT_ACADEMICS_ARTICLE: "EDIT_ACADEMICS_ARTICLE",
   DELETE_ACADEMICS_ARTICLE: "DELETE_ACADEMICS_ARTICLE",
 };
 
 export default academicsActionType