const admissionActionType = {
  SET_ALL_ADMISSION_ARTICLES: "SET_ALL_ADMISSION_ARTICLES",
  SET_ADMISSION_ARTICLE: "SET_ADMISSION_ARTICLE",
  LIKE_ADMISSION_ARTICLE: "LIKE_ADMISSIONN_ARTICLE",
  ADD_ADMISSION_ARTICLE: "ADD_ADMISSION_ARTICLE",
  EDIT_ADMISSION_ARTICLE: "EDIT_ADMISSION_ARTICLE",
};

export default admissionActionType