const careerActionType = {
   SET_ALL_CAREER_ARTICLES: "SET_ALL_CAREER_ARTICLES",
   ADD_CAREER_ARTICLE: "ADD_CAREER_ARTICLE",
   EDIT_CAREER_ARTICLE: "EDIT_CAREER_ARTICLE",
   DELETE_CAREER_ARTICLE: "DELETE_CAREER_ARTICLE",
 }
 
 export default careerActionType